### ISSUE TITLE
Show two way relationships between organizations

### ISSUE THREAD

**Issue by KatieMFritz** [flipboxfactory/organizations#14]
In my project, an organization may have one parent and many children. For example, Acme International might be a parent of Acme North America, Acme Asia, etc.

I want to be able to connect organizations from either direction, then see and edit the relationship from either side. So I want to add Acme International from Acme Asia, then see on the Acme International organization that Acme Asia is its child (and remove it from there if desired).

Previous setup:

- organizations were entries
- used [Many to Many plugin](https://github.com/Pageworks/craft-manytomany) to relate parents and children, so the relationship could be seen and edited from either organization

What's the best way to do that now?

**Comment by KatieMFritz** [comment]
Any ideas for this? Or a potential release date?

**Comment by nateiler** [comment]
I don't know of a great way to currently handle this and it likely won't become part of this plugin as it's a bit out of scope and probably better suited for something similar to the Many to Many plugin or Element List.

If using [Element List](https://github.com/flipboxfactory/craft-element-lists/issues) plugin is an option, create an issue there and we'll pick this up.
