### ISSUE TITLE
How to translate "Users" in Organizations Users tab?

### ISSUE THREAD

**Issue by KatieMFritz** [flipboxfactory/organizations#16]
My clients have requested we use the words Person/People instead of User/Users, since we're using the Craft site as a CRM and not everyone will log in. 

I'm using an English translation file (`translations/en/app.php`) to handle this throughout the Control Panel, but in the Organizations editor, the tab still says "Users".

![Screen Shot 2019-04-30 at 11 39 04 AM](https://user-images.githubusercontent.com/7085184/56974319-9f84c880-6b3c-11e9-8b3a-befff61d5c71.png)

This might be an issue with Tabs - because I name all the other tabs myself, I would guess they're not affected by the static translations. Do you have any ideas?

I'm not sure how hard this would be on your end, but allowing admins to customize the label of that tab would also work for this purpose.

**Comment by KatieMFritz** [comment]
And I know this is probably a stretch, but it would be sweet to be able to specify where in the tab order this tab appears! 😁

**Comment by KatieMFritz** [comment]
I see you have a filter applied in `src/cp/controllers/OrganizationTabsTrait.php`, but it doesn't seem to be actually getting translated.

```php
$tabs['users'] = [
                'label' => Craft::t('organizations', 'Users'),
                'url' => '#user-index'
            ];
```

**Comment by nateiler** [comment]
Good ideas.

Try adding that translation in `translations/en/organizations.php` in the meantime.

**Comment by KatieMFritz** [comment]
That totally worked, Nate!

**Comment by nateiler** [comment]
As of [v1.0.8](https://github.com/flipboxfactory/organizations/releases/tag/1.0.8) there is also a config value that can be set via `config/organizations.php`

```<?php

return [
    'usersTabOrder' => 2, // set the tab order
    'usersTabLabel' => 'Contacts' // set the tab label (without needing to use translations)
];```
