### ISSUE TITLE
Tabs not working on Organization create

### ISSUE THREAD

**Issue by dougstjohn** [flipboxfactory/organizations#5]
There are 2 separate flows that break during organization creation when multiple field tabs:

Plugin version: 1.0.0-rc.18

**FLOW 1:**
- Go to /admin/organizations
- Click 'New Organization' button.
- Click the gear in the right sidebar and enable an Organization Type.
- Select that Organization Type in the dropdown to the left.
- No tabs are shown. Only the first tab fields show.

> Uncaught TypeError: Craft.appendFootHtml is not a function
    at s.constructor.<anonymous> (OrganizationTypeSwitcher.min.js:1)

- Enable a second Organization Type.
- Select that Organization Type in the dropdown to the left.
- Spinner spins and no fields are updated.

> Uncaught TypeError: Cannot read property '$primaryForm' of undefined

**FLOW 2:**
- Go to /admin/organizations
- Click the down arrow on the 'New Organization' button.
- Select an Organization Type from the dropdown.
- None of the tabs on this page work.

> Uncaught TypeError: Craft.appendFootHtml is not a function

**Comment by nateiler** [comment]
Seems to be related to: https://github.com/craftcms/cms/issues/2966.

**Comment by nateiler** [comment]
Issue has been traced to: https://github.com/craftcms/cms/commit/6b446e83dd2bd426c269c893d446dbaaef2bae74#diff-9fb0aaf8b328a3f55c1157c12692e1ee

Patch applied via: https://github.com/flipboxfactory/craft-ember/commit/96e536da50d8e9f744c9cd506d86f953b27b20af
